# Generated by Django 5.0.2 on 2024-02-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SI_subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SI_subject_name', models.CharField(max_length=50)),
                ('SI_subject_address', models.CharField(max_length=200)),
                ('SI_subject_age', models.IntegerField()),
                ('SI_subject_gender', models.CharField(max_length=10)),
                ('SI_subject_offence', models.CharField(max_length=100)),
                ('SI_front_profile', models.CharField(max_length=1000)),
                ('SI_left_profile', models.CharField(max_length=1000)),
                ('SI_right_profile', models.CharField(max_length=1000)),
                ('SI_iris', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
