# Generated by Django 5.0.4 on 2024-04-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=100),
        ),
    ]
