# Generated by Django 5.0.4 on 2024-04-11 14:53

import camsafedata.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0003_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('offence', models.CharField(max_length=200)),
                ('aadhar_no', models.BigIntegerField(default=None, null=True)),
                ('date', models.DateField(null=True)),
                ('day', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('master_front_profile', models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camsafedata.subjectdetails')),
            ],
        ),
    ]
