# Generated by Django 5.0.2 on 2024-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0004_adminidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcTVIdentityTransaction',
            fields=[
                ('CTVIT_camera_number', models.IntegerField(max_length=20)),
                ('CTVIT_date_day', models.CharField(max_length=20)),
                ('CTVIT_footage_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CTVIT_footage', models.CharField(max_length=1000)),
                ('CTVIT_camera_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('FT_feature_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FT_subject_id', models.CharField(max_length=50)),
                ('FT_left_eye', models.CharField(max_length=50)),
                ('FT_right_eye', models.CharField(max_length=1000)),
                ('FT_nose', models.CharField(max_length=1000)),
                ('FT_lips', models.CharField(max_length=1000)),
                ('FT_left_eyebrow', models.CharField(max_length=1000)),
                ('FT_right_eyebrow', models.CharField(max_length=1000)),
                ('FT_left_ear', models.CharField(max_length=1000)),
                ('FT_right_ear', models.CharField(max_length=1000)),
                ('FT_hair_color', models.CharField(max_length=1000)),
                ('FT_eye_color', models.CharField(max_length=1000)),
                ('FT_beard', models.CharField(max_length=1000)),
                ('FT_mustache', models.CharField(max_length=1000)),
                ('FT_mole', models.CharField(max_length=1000)),
                ('FT_birth_mark', models.CharField(max_length=1000)),
                ('FT_hair', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('UI_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('UI_user_password', models.CharField(max_length=50)),
                ('UI_user_email_id', models.EmailField(max_length=60)),
                ('UI_name', models.CharField(max_length=50)),
                ('UI_police_center_code', models.IntegerField()),
                ('UI_contact_no', models.BigIntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_district',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_location_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_pin_code',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_taluka',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cctvidentitymaster',
            name='district',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cctvidentitymaster',
            name='pin_code',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cctvidentitymaster',
            name='state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cctvidentitymaster',
            name='taluka',
            field=models.CharField(max_length=40),
        ),
    ]
