# Generated by Django 5.0.4 on 2024-04-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0004_subjectdetails_proimage'),
        ('camsafedata', '0004_user_login_status'),
    ]

    operations = [
    ]
