# Generated by Django 5.0.2 on 2024-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0005_cctvidentitytransaction_featuredata_useridentity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentity',
            name='UI_contact_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
