# Generated by Django 5.0.2 on 2024-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0006_alter_useridentity_ui_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_district',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_location_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_state',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='adminidentity',
            name='AI_taluka',
            field=models.CharField(max_length=25),
        ),
    ]
