# Generated by Django 5.0.2 on 2024-02-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0008_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='CU_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='CU_fname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='CU_desc',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='CU_lname',
            new_name='name',
        ),
    ]
