# Generated by Django 5.0.2 on 2024-02-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0010_rename_ui_contact_no_useridentity_contactnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_admin_id',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_contact_no',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_admin_password',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_pin_code',
            new_name='pinCode',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_police_station_code',
            new_name='policeStationCode',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_police_station_name',
            new_name='policeStationName',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_location_name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_state',
            new_name='taluka',
        ),
        migrations.RenameField(
            model_name='adminidentity',
            old_name='AI_thana_incharge',
            new_name='thanaIncharge',
        ),
        migrations.RemoveField(
            model_name='adminidentity',
            name='AI_taluka',
        ),
        migrations.AddField(
            model_name='adminidentity',
            name='location',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
