# Generated by Django 5.0.3 on 2024-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0011_rename_ai_admin_id_adminidentity_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('SH_subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SH_subject_name', models.CharField(max_length=50)),
                ('SH_camera_location_name', models.CharField(max_length=50)),
                ('SH_date', models.CharField(max_length=20)),
                ('SH_day', models.CharField(max_length=20)),
                ('SH_footage_id', models.CharField(max_length=20)),
                ('SH_camera_id', models.CharField(max_length=15)),
                ('SH_detailed_view', models.CharField(max_length=50)),
            ],
        ),
    ]
