# Generated by Django 5.0.3 on 2024-03-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0012_subjecthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecthistory',
            name='SH_detailed_view',
        ),
    ]
