# Generated by Django 5.0.6 on 2024-05-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0014_rename_si_subject_id_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='SI_subject_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_subject_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_front_profile',
            new_name='front_profile',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_subject_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_iris',
            new_name='iris',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_left_profile',
            new_name='left_profile',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_subject_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_subject_offence',
            new_name='offence',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='SI_right_profile',
            new_name='right_profile',
        ),
    ]
