# Generated by Django 5.0.6 on 2024-05-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0015_rename_si_subject_address_subject_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='aadhar_no',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
