# Generated by Django 5.0.6 on 2024-05-26 01:12

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0016_subject_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='subject',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
    ]
