# Generated by Django 5.0.2 on 2024-05-28 06:04

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0019_alter_subject_master_front_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
    ]
