# Generated by Django 5.0.6 on 2024-06-02 13:39

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0021_alter_subject_master_front_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='aadhar_no',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
    ]
