# Generated by Django 5.0.6 on 2024-06-02 17:15

import camsafedata.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0022_alter_subject_master_front_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subjectdetails',
            name='date',
        ),
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='camsafedata.subjectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='camsafedata.subjectdetails')),
            ],
        ),
    ]
