# Generated by Django 5.0.6 on 2024-06-05 09:00

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0023_remove_subjectdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetails',
            name='date',
            field=models.DateField(default='2002-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectdetails',
            name='time',
            field=models.TimeField(default='02:02:02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.DeleteModel(
            name='DateEntry',
        ),
    ]
