# Generated by Django 5.0.6 on 2024-06-05 09:02

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0024_subjectdetails_date_subjectdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetails',
            name='address',
            field=models.TextField(default='Mumbai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
