# Generated by Django 5.0.6 on 2024-06-05 09:03

import camsafedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0025_subjectdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
