# Generated by Django 5.0.6 on 2024-06-06 10:52

import camsafedata.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsafedata', '0027_alter_subject_master_front_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='master_front_profile',
            field=models.ImageField(blank=True, null=True, upload_to=camsafedata.models.upload_path),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
